spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://192.168.1.74:3306/agenciaviajes?serverTimezone=UTC
    username: luis
    password: luis
  jpa:
    hibernate:
      naming:
        implicit-strategy: org.hibernate.boot.model.naming.ImplicitNamingStrategyLegacyJpaImpl
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
  application:
    name: servicio-vuelos
  mvc:
    pathmatch:
      matching-strategy: ant-path-matcher
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
  instance:
    instanceId: ${random.value}:${spring.application.name} 
  
server:
  port: ${port:0}
